### ISSUE TITLE
ERROR: lazy loading failed for package 'tune' 

### ISSUE THREAD

**Issue by NetZissou** [tidymodels/tune#117]
< -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

## ERROR: lazy loading failed for package 'tune' 
Hi, I am having trouble with installing the tune package from Github. It appears that `ERROR: lazy loading failed for package 'tune'`.
Here are the details:
√  checking for file 'C:\Users\Administrator\AppData\Local\Temp\RtmpS45S3z\remotesc690e6d33d7\tidymodels-tune-532c690/DESCRIPTION' ...
-  preparing 'tune':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'tune_0.0.0.9003.tar.gz'
   
* installing *source* package 'tune' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'cli' 1.1.0 is being loaded, but >= 1.9.9.9000 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
停止执行
ERROR: lazy loading failed for package 'tune'
* removing 'C:/Program Files/R/R-3.6.1/library/tune'
Error: Failed to install 'tune' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ADMINI~1/AppData/Local/Temp/RtmpS45S3z/filec6905f1b64ab/tune_0.0.0.9003.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by topepo** [comment]
As the error says, you need the development version of `cli`. Install the `devtools` package from CRAN and use `install_dev("cli")`

**Comment by NetZissou** [comment]
> As the error says, you need the development version of `cli`. Install the `devtools` package from CRAN and use `install_dev("cli")`
Thanks, I have noticed that, however, I checked the cran that the latest version of `cli` is 1.1.0. I have reinstall it, but still can have the `tune` package installed.

**Comment by topepo** [comment]
1.9.9.9000 > 1.1.0 so you need the devel version on github (assuming that you mean that you reinstalled the CRAN version).

**Comment by davechilders** [comment]
@NetZissou try `devtools::install_github("r-lib/cli")`

**Comment by topepo** [comment]
closed due to inactivity
