### ISSUE TITLE
optimize iterators

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#16]
In cases where there are a lot of workers and a fast pre-processor, collapse the `for` loops and parallel process over all combinations. Also, if there is a single resample, we should iterate over the parameters. 

`tune_grid()` should be able to have good heuristics on what the best approach would be _given the tuning grid_. In the future, we should have more workflows and have `quarterback()` be able to more dynamically determine the appropriate items to iterate over.

**Comment by kkmann** [comment]
+1 for making this configurable. Might not be the most efficient, but given enough resources, flattening the array and running everything in parallel should be the quickest, right?

**Comment by juliasilge** [comment]
As of tune 0.1.2, the [`control_` functions now have a `parallel_over` argument](https://tune.tidymodels.org/reference/control_grid.html):

> A single string containing either `"resamples"` or `"everything"` describing how to use parallel processing. Alternatively, `NULL` is allowed, which chooses between `"resamples"` and `"everything"` automatically.
>
> If `"resamples"`, then tuning will be performed in parallel over resamples alone. Within each resample, the preprocessor (i.e. recipe or formula) is processed once, and is then reused across all models that need to be fit.
>
> If `"everything"`, then tuning will be performed in parallel at two levels. An outer parallel loop will iterate over resamples. Additionally, an inner parallel loop will iterate over all unique combinations of preprocessor and model tuning parameters for that specific resample. This will result in the preprocessor being re-processed multiple times, but can be faster if that processing is extremely fast.
>
> If `NULL`, chooses `"resamples"` if there are more than one resample, otherwise chooses `"everything"` to attempt to maximize core utilization.

You can read more about using `parallel_over` in [this blog post](https://www.tidyverse.org/blog/2020/11/tune-parallel/).
