### ISSUE TITLE
shinytune package? 

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#162]
Create a small, separate package that takes the results of one of the `tune_*` objects and uses shiny to explore the hyperparameter values to pick a good one (since `autoplot()` is... sub-optimal). 

This is the the same spirit of `shinystan`.

**Comment by Jim89** [comment]
Does "help wanted" indicate help from anyone, or help from tidymodels team members? I'd be interested in working on this if it's the former.

**Comment by topepo** [comment]
We'll take all of the help that we get. Let me know if you have any questions.

**Comment by Jim89** [comment]
Ok great. I've used `tune` a bit (a slightly earlier version) and `shinystan` a little as well, this weekend I'll spend some time digging in to what `tune_` objects are returning and think about/sketch out what would be useful to enable exploration of interactively.

**Comment by Jim89** [comment]
Starting to look at this today. I've created https://github.com/Jim89/shinytune to hold my progress for now, and will start working through what might be sensible to include/exclude

**Comment by topepo** [comment]
Here are my thoughts: 

For any model generated by the `tune_*` functions, I would have a graph of the tuning parameters for a selected metric. Perhaps a scatterplot matrix? 

For regression, I would get the predicted values (`collect_metrics(x, summarize = TRUE)`), compute the residuals, then generate plots of the observed x predicted and residuals x predicted. Using `plotly` or `ggiraph` to make them interactive would be a good idea too. If the object is from one of the `tune` functions, I'd give them a way to select a tuning parameter combination. 

For classification, it depends on the type of metrics. If classification, some way to explore the out-of-sample predictions (`collect_metrics()` again) versus the predictors. When there are class probabilities, scatterplots and histograms would be a good idea. Otherwise... not sure.

**Comment by topepo** [comment]
This is going to worked on by a summer intern

**Comment by Jim89** [comment]
Thanks; and sorry that I didn't progress beyond the basics on this. Hopefully I didn't actively block anything (and I'm very sorry if I did).

**Comment by juliasilge** [comment]
No worries at all @Jim89! 🙌
