### ISSUE TITLE
sample_size and sample_prop in boost_tree

### ISSUE THREAD

**Issue by williamorim** [tidymodels/tune#179]
## The problem

I'm having trouble with `sample_size()` and `sample_prop()` on `boost_tree()` model with the `xgboost`engine. 

The `boost_tree()` function takes only a `sample_size` argument. This argument can recieve both number or proportion of data that is exposed to the fitting process.

When setting a proportion range to this parameter (e.g., 0.5 to 0.9), one must use `sample_size = sample_prop(c(0.5, 0.9))`? 

`sample_size = sample_size(c(0.5, 0.9))` returns only ones and zeros to `sample_size` when a grid is made.

I think `sample_size = sample_prop(c(0.5, 0.9))` works, but I've struggled a little to understand. This is not clear in the documentation.

Issues aside, thank you very much for the great package!

## Reproducible example

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'xts':
#>   method     from
#>   as.zoo.xts zoo
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.0 ──
#> ✓ broom     0.5.4     ✓ recipes   0.1.9
#> ✓ dials     0.0.4     ✓ rsample   0.0.5
#> ✓ dplyr     0.8.4     ✓ tibble    2.1.3
#> ✓ ggplot2   3.2.1     ✓ tune      0.0.1
#> ✓ infer     0.5.1     ✓ workflows 0.1.0
#> ✓ parsnip   0.0.5     ✓ yardstick 0.0.5
#> ✓ purrr     0.3.3
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard()  masks scales::discard()
#> x dplyr::filter()   masks stats::filter()
#> x dplyr::lag()      masks stats::lag()
#> x ggplot2::margin() masks dials::margin()
#> x recipes::step()   masks stats::step()

recipe <- recipe(mpg ~ ., data = mtcars)

mod_xgboost <- boost_tree(
  mtry = 3,
  trees = tune(),
  min_n = tune(),
  tree_depth = tune(),
  learn_rate = tune(),
  loss_reduction = tune(),
  sample_size = tune()
) %>% 
  set_mode("classification") %>% 
  set_engine("xgboost")

workflow_xgboost <- workflow() %>%
  add_recipe(recipe) %>%
  add_model(mod_xgboost)

hp_xgboost_size <- workflow_xgboost %>% 
  parameters() %>% 
  update(
    sample_size = sample_size(c(0.5, 0.9))
  )

hp_xgboost_prop <- workflow_xgboost %>% 
  parameters() %>% 
  update(
    sample_size = sample_prop(c(0.5, 0.9))
  )

grid_size <- grid_regular(hp_xgboost_size, levels = 5)
grid_prop <- grid_regular(hp_xgboost_prop, levels = 5)

unique(grid_size$sample_size)
#> [1] 0

unique(grid_prop$sample_size)
#> [1] 0.5 0.6 0.7 0.8 0.9
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       macOS Catalina 10.15.1      
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Araguaina           
#>  date     2020-03-03                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package       * version    date       lib source        
#>  tidymodels    * 0.1.0      2020-02-16 [1] CRAN (R 3.6.0)
#>  tune          * 0.0.1      2020-02-11 [1] CRAN (R 3.6.0)
```

</details>

**Comment by topepo** [comment]
Sorry, this was fixed a while back in the `tunable` [method](https://github.com/tidymodels/tune/blob/3c14c13ea46ac2436c0aaec3ce3a3994cc6936dd/R/tunable.R#L296). It uses `sample_prop()` be default when you get the parameter object.

**Comment by jaredlander** [comment]
I'm running into a similar problem when trying to a boost `C5.0` model. In the `tunable` method, should we add a line in the `C5.0` check to also use `sample_prop()`?

According to the [docs](https://parsnip.tidymodels.org/reference/boost_tree.html) this happens automatically for `xgboost` as is evidenced in the `tunable` method. But `C5.0` needs `sample` as a [proportion too](https://topepo.github.io/C5.0/reference/C5.0Control.html). Yet with `{parsnip}` it is left as a number using `sample_size()` instead of `sample_prop()`.

If I use `update()` on the parameters of a `C5.0` workflow and pass that to `tune_grid()` it works as expected, but not if I leave the default.

Back to the `tunable` method, I *think* it would look like this.

```r
tunable.boost_tree <- function(x, ...) {
  res <- NextMethod()
  if (x$engine == "xgboost") {
    res$call_info[res$name == "sample_size"] <-
      list(list(pkg = "dials", fun = "sample_prop"))
  } else {
    if (x$engine == "C5.0") {
      res$call_info[res$name == "trees"] <-
        list(list(pkg = "dials", fun = "trees", range = c(1, 100)))

      res$call_info[res$name == "sample_size"] <-
        list(list(pkg = "dials", fun = "sample_prop"))
    }
  }
  res
}
```
