### ISSUE TITLE
error tuning model AND recipe

### ISSUE THREAD

**Issue by ericpgreen** [tidymodels/tune#182]
##  The problem

I get the following error when I try to tune a recipe _and_ model:

> Error: Some tuning parameters require finalization but there are recipe parameters that require tuning. Please use parameters() to finalize the parameter ranges.

I originally posted to [RStudio Community](https://community.rstudio.com/t/understanding-tune-update-model-and-parameters/55912?u=ericpgreen) because I was following [an example from the tidymodels workshop deck on tuning](https://conf20-intro-ml.netlify.com/materials/) and figured I was making a mistake. But one of the deck authors [confirmed that she was seeing the same problem](https://community.rstudio.com/t/understanding-tune-update-model-and-parameters/55912/2?u=ericpgreen).

## Reproducible example

Alison made a nice reprex:

```r
library(modeldata)
data("stackoverflow")
library(tidyverse)
library(tidymodels)
set.seed(100) # Important!

# make smaller to save time
so_split <- initial_split(sample_n(stackoverflow, size = 300), 
                          strata = Remote)
so_train <- training(so_split)
so_test  <- testing(so_split)
# again, simpler so runs faster
so_folds <- vfold_cv(so_train, v = 2, strata = Remote)

so_rec <- recipe(Remote ~ ., 
                 data = so_train) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_lincomb(all_predictors()) %>% 
  step_downsample(Remote)

tune_rec <- recipe(Remote ~ ., 
                   data = so_train) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_lincomb(all_predictors()) %>% 
  step_downsample(Remote, under_ratio = tune())

# no tuning
rf_spec <- 
  rand_forest() %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

# add tuning
tune_spec <-
  rand_forest(mtry = tune(),
              min_n = tune()) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

# define 3 workflows
tuneboth_wf <-
  workflow() %>% 
  add_recipe(tune_rec) %>% 
  add_model(tune_spec)

tunerec_wf <-
  workflow() %>% 
  add_recipe(tune_rec) %>% 
  add_model(rf_spec)

tunemod_wf <-
  workflow() %>% 
  add_recipe(so_rec) %>% 
  add_model(tune_spec)

# this won't work
tuneboth_wf %>% 
  tune_grid(resamples = so_folds)

# works
tunerec_wf %>% 
  tune_grid(resamples = so_folds)

# works
tunemod_wf %>% 
  tune_grid(resamples = so_folds)
```

**Comment by topepo** [comment]
This is explained in the help file for _tune_grid_: 

> In some cases, the tuning parameter values depend on the dimensions of the data. For example, `mtry` in random forest models depends on the number of predictors. In this case, the default tuning parameter object requires an upper range. `dials::finalize()` can be used to derive the data-dependent parameters. Otherwise, a parameter set can be created (via `dials::parameters()` and the dials `update()` function can be used to change the values. This updated parameter set can be passed to the function via the param_info argument.

and the error message is pretty informative: 

> Error: Some tuning parameters require finalization but there are recipe parameters that require tuning. Please use `parameters()` to finalize the parameter ranges.

It points to the file that shows you how to finalize the parameters. 

Here's an example: 

``` r
library(modeldata)
data("stackoverflow")
library(tidyverse)
library(tidymodels)
#> ── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────── tidymodels 0.1.0 ──
#> ✓ broom     0.5.4     ✓ rsample   0.0.5
#> ✓ dials     0.0.4     ✓ tune      0.0.1
#> ✓ infer     0.5.1     ✓ workflows 0.1.0
#> ✓ parsnip   0.0.5     ✓ yardstick 0.0.5
#> ✓ recipes   0.1.9
#> ── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
#> x scales::discard()   masks purrr::discard()
#> x dplyr::filter()     masks stats::filter()
#> x recipes::fixed()    masks stringr::fixed()
#> x dplyr::lag()        masks stats::lag()
#> x dials::margin()     masks ggplot2::margin()
#> x yardstick::spec()   masks readr::spec()
#> x recipes::step()     masks stats::step()
#> x recipes::yj_trans() masks scales::yj_trans()
set.seed(100) # Important!

# make smaller to save time
so_split <- initial_split(sample_n(stackoverflow, size = 300), 
                          strata = Remote)
so_train <- training(so_split)
so_test  <- testing(so_split)
# again, simpler so runs faster
so_folds <- vfold_cv(so_train, v = 2, strata = Remote)

so_rec <- recipe(Remote ~ ., 
                 data = so_train) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_lincomb(all_predictors()) %>% 
  step_downsample(Remote)

tune_rec <- recipe(Remote ~ ., 
                   data = so_train) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_lincomb(all_predictors()) %>% 
  step_downsample(Remote, under_ratio = tune())

# no tuning
rf_spec <- 
  rand_forest() %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

# add tuning
tune_spec <-
  rand_forest(mtry = tune(),
              min_n = tune()) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

# define 3 workflows
tuneboth_wf <-
  workflow() %>% 
  add_recipe(tune_rec) %>% 
  add_model(tune_spec)

tuneboth_param <- parameters(tuneboth_wf)
tuneboth_param
#> Collection of 3 parameters for tuning
#> 
#>           id parameter type object class
#>         mtry           mtry    nparam[?]
#>        min_n          min_n    nparam[+]
#>  under_ratio    under_ratio    nparam[+]
#> 
#> Model parameters needing finalization:
#>    # Randomly Selected Predictors ('mtry')
#> 
#> See `?dials::finalize` or `?dials::update.parameters` for more information.

tuneboth_param <- 
  tuneboth_param %>% 
  # Pick an upper bound for mtry: 
  update(mtry = mtry(c(1, 20)))

# this won't work
tuneboth_wf %>% 
  tune_grid(resamples = so_folds, param_info = tuneboth_param)
#> #  2-fold cross-validation using stratification 
#> # A tibble: 2 x 4
#>   splits            id    .metrics          .notes          
#> * <list>            <chr> <list>            <list>          
#> 1 <split [112/113]> Fold1 <tibble [20 × 6]> <tibble [0 × 1]>
#> 2 <split [113/112]> Fold2 <tibble [20 × 6]> <tibble [0 × 1]>
```

<sup>Created on 2020-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ericpgreen** [comment]
Thanks for taking the time to explain it, @topepo. 

No need to explain further because it's probably something that will make sense to me as I study it a bit more, but it seems to me that if the lack of an upper bound for `mtry` is the problem, then`tunemod_wf` should fail as well (it's the workflow that only includes `tune()` in the model). But it works.

**Comment by topepo** [comment]
`tunemod_wf` doesn't fail since it does not have tuning parameters in the recipe. In that case it knows the dimensions of the data (since the recipe can be prepared) and run `finalize()` without any ambiguity. 

If there are tuning parameters, the recipe cannot be prepared beforehand and the parameters cannot be finalized. 

Complicated! However, that's how things are in model-land a lot, especially when we enable complex stuff (like tuning the pre-processing steps).
