### ISSUE TITLE
control_resamples doesn't work as other control_*

### ISSUE THREAD

**Issue by cimentadaj** [tidymodels/tune#183]
First, thanks for `tidymodels`! You're open source work is very valuable to the community. 

## The problem

I was trying to use `tune::control_resamples()` similarly as `parsnip::control_parsnip()` but noticed that none of the `tune::control_*` functions have a custom class similar to `parsnip::control_parsnip()` nor a custom printout.

Have you considered making them work similarly? 

## Reproducible example

```r
library(parsnip)
library(tune)

control_parsnip()
#> parsnip control object
class(control_parsnip())
#> [1] "control_parsnip"

control_resamples()
#> $verbose
#> [1] FALSE
#> 
#> $allow_par
#> [1] TRUE
#> 
#> $extract
#> NULL
#> 
#> $save_pred
#> [1] FALSE
#> 
#> $pkgs
#> NULL
class(control_resamples())
#> [1] "list"

control_grid()
#> $verbose
#> [1] FALSE
#> 
#> $allow_par
#> [1] TRUE
#> 
#> $extract
#> NULL
#> 
#> $save_pred
#> [1] FALSE
#> 
#> $pkgs
#> NULL
class(control_grid())
#> [1] "list"
```

If you're interested I could send a PR with the same structure as `parsnip::control_parsnip()`.

**Comment by topepo** [comment]
A PR would be great.

**Comment by topepo** [comment]
Thanks!
