### ISSUE TITLE
Sparsity for tuning

### ISSUE THREAD

**Issue by ThomasWolf0701** [tidymodels/tune#198]
Currently the tuning step does not seem to support sparsity, as the rsample package need
a data frame as input:

```
#defne training test split
train_test_split <-
  rsample::initial_split(
    data = fingerprintsAll,     
    prop = 0.80   
  ) 

And for instance the tune bayes needs an resample object: 
xgb_search <- tune_bayes(xgb_workflow, 
                         resamples = ames_vfold,
                         initial = 25, iter = 50,
                         param_info = xgb_param,
                         control = ctrl)
```
There are functions like juice() and bake() that can export dgcMatrix so it seems to be supported
somehow. Is it possible to specify somewhere that a data frame is transformed to a dgcMatrix
before passing it into the model (i.e. xgboost). Maybe in the recipe or workflow packages. ?

**Comment by topepo** [comment]
We are working on using sparse structures _inside_ of recipes steps but we are unlikely to support starting with sparse matrix structures. That is generally antithetical to the principles and methods of the tidyverse. 

That said, we might be able to get you to what you want once the recipe parts are in place. It would be good to know more about where your data first started (e.g. are these molecular fingerprints or something else?)

**Comment by ThomasWolf0701** [comment]
That would be great. The data are indeed molecular fingerprints.

**Comment by juliasilge** [comment]
The tune functions can now pass sparse and dense matrix structures around for fitting/tuning. Check out tidymodels/tidymodels#42 for more details! 🚀
