### ISSUE TITLE
Issue with tune_grid giving different results with a simple recipe versus formula

### ISSUE THREAD

**Issue by LucyMcGowan** [tidymodels/tune#199]
I am seeing an issue when I use a simple recipe (that only includes a formula) versus passing the formula itself to `tune_grid()` with `xgboost`. When I use the recipe, the models fail, when I use the formula, it seems to work. Below is a small reprex. 

(It is possible this is somewhat related to #151) 

``` r
suppressPackageStartupMessages(library(tidymodels))
library(ISLR)

carseat_cv <- vfold_cv(Carseats)

boost_spec <- boost_tree(
  mode = "regression",
  trees = tune()) %>%
  set_engine("xgboost")

model_rec <- recipe(Sales ~ .,
                    data = Carseats)

## Model with formula works
model_form <- tune_grid(boost_spec,
                          Sales ~ .,
                          resamples = carseat_cv)

## Model with simple recipe fails
model_rec <- tune_grid(boost_spec,
                       preprocessor = model_rec,
                       resamples = carseat_cv)
#> x Fold01: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold02: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold03: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold04: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold05: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold06: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold07: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold08: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold09: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> x Fold10: model 1/1: Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): 'd...
#> Warning: All models failed in tune_grid(). See the `.notes` column.
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by EmilHvitfeldt** [comment]
Recipes don't deal with factors by default, this means that `xgboost::xgb.DMatrix` will receive a matrix that looks like this: 

```r
    CompPrice Income Advertising Population Price ShelveLoc Age  Education Urban US   
[1,] "138"     " 73"  "11"        "276"      "120" "Bad"     "42" "17"      "Yes" "Yes"
[2,] "111"     " 48"  "16"        "260"      " 83" "Good"    "65" "10"      "Yes" "Yes"
[3,] "113"     " 35"  "10"        "269"      " 80" "Medium"  "59" "12"      "Yes" "Yes"
[4,] "117"     "100"  " 4"        "466"      " 97" "Medium"  "55" "14"      "Yes" "Yes"
[5,] "141"     " 64"  " 3"        "340"      "128" "Bad"     "38" "13"      "Yes" "No" 
[6,] "124"     "113"  "13"        "501"      " 72" "Bad"     "78" "16"      "No"  "Yes"
```

Adding a `step_dummy()` to your recipe will rectify that problem.

``` r
suppressPackageStartupMessages(library(tidymodels))
#> Warning: package 'rsample' was built under R version 3.6.2
#> Warning: package 'tibble' was built under R version 3.6.2
library(ISLR)

carseat_cv <- vfold_cv(Carseats)

boost_spec <- boost_tree(
  mode = "regression",
  trees = tune()) %>%
  set_engine("xgboost")

model_rec <- recipe(Sales ~ .,
                    data = Carseats) %>%
  step_dummy(all_nominal())

## Model with formula works
model_form <- tune_grid(boost_spec,
                        Sales ~ .,
                        resamples = carseat_cv)

## Model with simple recipe fails
model_rec <- tune_grid(boost_spec,
                        preprocessor = model_rec,
                        resamples = carseat_cv)
```

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by LucyMcGowan** [comment]
Ah, sorry 😐 this is the second time I’ve hit this https://github.com/tidymodels/recipes/issues/476

Both times have been related to student confusion, I wonder if there is a way we could document that plugging in the recipe may result in different behavior than the formula due to specific preprocessing done by the engine 🤔 if you think that’d be helpful I’d be happy to draft. Also happy to just try to remember to teach this better so I don’t end up accidentally posting another issue in a few months.

**Comment by topepo** [comment]
I've started to document this in the various packages (esp for trees and similar models). For the upcoming `rules` package, we have

> Note that `C5_rules()` does not require that categorical predictors be  converted to numeric indicator values. Note that using [parsnip::fit()] will  _always_ create dummy variables so, if there is interest in keeping the  categorical predictors in their original format, [parsnip::fit_xy()] would  be a better choice. When using the `tune` package, using a recipe for  pre-processing enables more control over how such predictors are encoded  since recipes do not automatically create dummy variables.

(edits are welcome)

As we make new releases, I'll add this to different man files

**Comment by topepo** [comment]
tidymodels/parsnip#290 will also address this
