### ISSUE TITLE
Feature Request: Could the valuereturned from parameters(..) include dummy functions for all .$object[[..]]$trans$transform and $inverse for all parameters

### ISSUE THREAD

**Issue by UnclAlDeveloper** [tidymodels/tune#200]
Would it be possible to create dummy *transform* and *inverse* functions for all the parameters returned by a call to parameters(recipe/model/workflow).  These would just be *function(x) x* for non integers and *function(x) as.integer(x)* for integer parameters.

This would make it easier to visualize and work with multiple hyper-parameters as they should be fairly linear if the transform (or dummy non-transform) can be easily applied.

**Comment by topepo** [comment]
I think that you would be better off making parameter sets/grids from the `parameters` object and using the standard R infrastructure (or a recipe) to decide how to encode these data.
