### ISSUE TITLE
Feature Request: As an extension to issue #200, could autoplot use the transforms of the hyperparameters

### ISSUE THREAD

**Issue by UnclAlDeveloper** [tidymodels/tune#201]
Autoplot currently uses the raw values of the hyper-parameters when producing the plot.  Unfortunately this means that hyper-parameters that use log transformations, such as penalty for glmnet, end up all scrunched at about zero, making it fairly unreadable.

**Comment by topepo** [comment]
We are working on this. I think that the solution will be to add the `parameters` object as an attribute to the tune object. From there `autoplot()` will be able to put the parameters into their transformed units.

**Comment by topepo** [comment]
Closed by #222
