### ISSUE TITLE
Feature Request:  Is there any investigation into creating a "hypertune space" for the hypertune parameters from random or grid hypertunes

### ISSUE THREAD

**Issue by UnclAlDeveloper** [tidymodels/tune#202]
I imagine there are papers that explore this, I just don't know about them.  It would seem evident that the reason for using random grids, wouldn't be because it would find the best parameter set, but rather that it would be the best for creating a model to estimate the best hyper-parameters and create a hypertune space to estimate the performance of different combinations of parameters. Is there much research on this and best practices?  I'm currently using kknn after giving up on cv.glmnet.

**Comment by topepo** [comment]
I'm not sure that you mean. 

Are you asking to take grid results and model them?

**Comment by UnclAlDeveloper** [comment]
Yes.  I can’t say it any other way.

**Comment by topepo** [comment]
That's what `tune_bayes()` does using a Gaussian process model.

**Comment by UnclAlDeveloper** [comment]
I haven’t used tune_bayes().  I thought that it was an alternative to grid and random searches.  Better than them but unable to work in parallel.  The reference link to tune_bayes() is broken, but looking at the example I guess the param_info could be seeded with the best results from a random grid?  But with CPU’s being so cheap, a spot instance on AWS is about a cent per cpu per hour (I’m basing that on c5.12xlarge), and getting cheaper every year, it would seem to make some sense just to run one of the random grids on as many cores as you can (49c/hour for 48) and then model the hyper tuning grid.  So I am interested in what investigation has been done on this, and if there are any recommendations?

**Comment by topepo** [comment]
For modeling the results of performance results I would use google scholar to look at autoML methods or "racing methods".
