### ISSUE TITLE
Is there a way to tune the optional arguments passed to set_engine?

### ISSUE THREAD

**Issue by kylegilde** [tidymodels/tune#213]
Hi,

I was trying to find an example of how to tune the "optional arguments associated with the chosen computational engine" in set_engine? Is this possible to do in the first place? 

Thanks

**Comment by py9mrg** [comment]
I'm new to tidymodels so not sure this will work, but have you tried declaring the arguments as available for tuning? Like `set_engine("glmnet", nlambda = tune())` and then defining a grid to be used by `tune_grid`?

**Comment by topepo** [comment]
This does/did work when I last tried it. I went make a reprex and it failed so I'll take a look. You should definitely be able to do this.

**Comment by kylegilde** [comment]
I appreciate it. It didn't work when I tried it with tune_bayes, but I'm very new to tidymodels. Thank you!

**Comment by juliasilge** [comment]
This has been fixed in #232! 🎉  Check out [NEWS](https://github.com/tidymodels/tune/blob/master/NEWS.md):

> In concert with dials > 0.0.7, tuning engine-specific arguments is possible. Many known engine-specific tuning parameters and handled automatically.

Give it a go, and please open a new issue if something isn't working.
