### ISSUE TITLE
tune_bayes() link doesn't work in pkgdown

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/tune#220]
https://tune.tidymodels.org/reference/tune_bayes.html
<img width="1210" alt="Screen Shot 2020-05-29 at 4 13 21 PM" src="https://user-images.githubusercontent.com/14034784/83312501-5a134e80-a1c7-11ea-8911-8ce7cc9958c5.png">

**Comment by juliasilge** [comment]
This is because of the file being called `tune_Bayes.R`.

**Comment by topepo** [comment]
This is changed in #219

**Comment by juliasilge** [comment]
We had a CRAN release 6 days ago and this is still broken. The file is still called `tune_Bayes.html` instead of `tune_bayes.html`, which you [can see here](https://github.com/tidymodels/tune/tree/master/docs). I'm going to mark this as something to fix for the next release.

**Comment by juliasilge** [comment]
Closed in #290
