### ISSUE TITLE
How to attain maximum CPU utilisation in Parallel Processing

### ISSUE THREAD

**Issue by robyjos** [tidymodels/tune#234]
Hi
I am trying to utilize the maximum cores available for tuning my grid. However, even after registering all the cores (either by DoParallel or DoFuture) it only uses cores equivalent to the resampling loop of grid search. Is this by design or is there a way to expand the run to all cores and improve efficiency?

Thanks

**Comment by JalalAl-Tamimi** [comment]
Hi
Following on this,
I also seem to be restricted in maximum number of CPUs used for tuning. I am using an HPC cluster with 44 cores, and in my tune_grid, I am running a 10-folds cross-validation (random forests with ranger). The CPU load shows that the job is always restricted to 10 CPUs although the code correctly detected the assigned 44 cores (registered with the future package). I am using R 4.0.0, tidymodels 0.1.0, tune 0.1.0.
It would be great if we can have an "n.threads" option in tune_grid.
Thanks

**Comment by topepo** [comment]
Take a look at #16. 

Right now, it is optimized for cases where preprocessing is costly. We will be provide an option to "flatten" the loops over resamples and parameters. However, that might be counter-productive in some instances. 

I'll also be adding racing methods so that this will go faster in either instance.

**Comment by topepo** [comment]
> It would be great if we can have an "n.threads" option in tune_grid.

You do. Using the parallel backends for `foreach`, they have arguments for how many cores to use. For example: 

```r
library(doMC)
registerDoMC(cores=parallel::detectCores())
```

**Comment by JalalAl-Tamimi** [comment]
Many thanks indeed for this. After sending you the email, I saw that parallel computing is by default (under tune_grid)
Yes this is what I do. I am using an HPC cluster, and declare a parallel backend with the future package.
So I do the following:
Library(future)
allCores <- parallel::detectCores()
registerDoFuture()
cl <- makeCluster(all_cores)
plan(cluster, workers = cl)

This detects the allocated CPU. In this case, I requested 44 Cores. 

When running the model, and tune the hyperparameters, with a 10-folds cross validation, this only uses 10 cores out of the assigned 44. The model takes roughly 35 minutes to run. I tried restricting to 10 cores, and obtained the same performance. This is what puzzles me. Why it is not using the full 44 cores. Each Core is assigned 2.5GB memory. So possibly, 10 cores with 25 GB memory is enough for the data. But the question above seems to suggest the same, i.e., not being able to use all cores...

Thanks

Jalal


Sent from Mail for Windows 10

**Comment by topepo** [comment]
As I've said above, we currently parallelize over resamples so that we do not repeat calculations. We will be creating other apis where you can repeat those calculations (assuming they are not expensive).

**Comment by JalalAl-Tamimi** [comment]
OK thanks for this and yes makes sense.

Jalal

**Comment by kkmann** [comment]
I ran into the same problem, it's documented but whether the default is sensible indeed very much depends on the situation.

With many cores and cheap pre-processing a flat loop woud definitely be the better option, albeit not the most efficient. Is there a workaround for now? I was trying to dig into the code, but that is a bit past my current understanding of rlang + co. I mean, in principle, one could just expand the parameters + folds and furrr over it... Defeats the purpose of using tidymodels/tune a bit though x)

**Comment by topepo** [comment]
You can test this in the current dev version of `tune`. There is an options in `control_grid()` to switch between the two approaches. I have some benchmarks that I'm working on that will be in the release blog post.

**Comment by juliasilge** [comment]
As of tune 0.1.2, the [`control_` functions now have a `parallel_over` argument](https://tune.tidymodels.org/reference/control_grid.html):

> A single string containing either `"resamples"` or `"everything"` describing how to use parallel processing. Alternatively, `NULL` is allowed, which chooses between `"resamples"` and `"everything"` automatically.
>
> If `"resamples"`, then tuning will be performed in parallel over resamples alone. Within each resample, the preprocessor (i.e. recipe or formula) is processed once, and is then reused across all models that need to be fit.
>
> If `"everything"`, then tuning will be performed in parallel at two levels. An outer parallel loop will iterate over resamples. Additionally, an inner parallel loop will iterate over all unique combinations of preprocessor and model tuning parameters for that specific resample. This will result in the preprocessor being re-processed multiple times, but can be faster if that processing is extremely fast.
>
> If `NULL`, chooses `"resamples"` if there are more than one resample, otherwise chooses `"everything"` to attempt to maximize core utilization.

You can read more about using `parallel_over` in [this blog post](https://www.tidyverse.org/blog/2020/11/tune-parallel/).
