### ISSUE TITLE
Question: tune()+reticulate Keras RNN via Python

### ISSUE THREAD

**Issue by Steviey** [tidymodels/tune#285]
**R 4.x, Ubuntu 16.x LTS**

Hello folks from tune(),
I search some dozenz sites for this.

Is it possible to use tidymodels::tune() to realize a bayesian search on a RNN model, created with reticulated Keras (aka rKeras) via Python? And if so, is there an example available?

Thank you and tidy on :-).

**Comment by topepo** [comment]
We have not implemented RNNs in `parsnip` so not at this time. You are welcome to create a `parsnip` PR for that model though. If you do, consider the existing [R wrapper for mlp's](https://github.com/tidymodels/parsnip/blob/cf623814cb6ca51eba0c0174fcab8cbed797fb54/R/mlp.R#L262) as a template.
