### ISSUE TITLE
Documentation for `tune_grid()`

### ISSUE THREAD

**Issue by simonschoe** [tidymodels/tune#324]
## The problem

In my opinion the documentations for `tune_grid()` are slightly misleading:

> When provided, the grid should have column names for each parameter and these should be named by the parameter name or `id`. For example, if a parameter is marked for optimization using `penalty = tune()`, there should be **a column names `tune`**.

According to the example provided in the sentence, the column should have been named `penalty` right?

**Comment by juliasilge** [comment]
Thank you for this report! 🙌  This was fixed in #260 but is not yet on CRAN. We are working on a CRAN release ASAP.
