### ISSUE TITLE
time_limit causes the entire script to halt?

### ISSUE THREAD

**Issue by kylegilde** [tidymodels/tune#337]
Hi, 
I ran my script from the command line, and it seems like time_limit in control_bayes() causes the entire script to halt. The script didn't save the results object.  Is this expected behavior? Thanks

```r
── Iteration 7 ──────────────────────────────────────────────────────────────

i Current best:         pr_auc=0.6992 (@iter 6)
i Gaussian process model
✓ Gaussian process model
i Generating 5000 candidates
i Predicted candidates
i trees=276, min_n=10, tree_depth=9, learn_rate=0.0664, mtry=0.87,
  sample_size=0.6, loss_reduction=12.1
i Estimating performance
✓ Estimating performance
Error: The time limit of 180 minutes has been reached.
x Optimization stopped prematurely; returning current results.
Timing stopped at: 8.695e+04 195.2 1.099e+04
Execution halted

**Comment by topepo** [comment]
It is not the intent. The instructions to stop use `stop()` and the [`on.exit()`](https://github.com/tidymodels/tune/blob/063d802ff047599f8727cfcd0d08a34534733c69/R/tune_bayes.R#L226) code don't use `quit()` or anything. Can you give us a reprex?

**Comment by juliasilge** [comment]
Thanks for this report! 🙌 If you or others in the future run into this problem, we are definitely interested in getting to the problem of it. A report with a [reprex](https://www.tidyverse.org/help/) will help us understand the nature of the problem and solve it.
