### ISSUE TITLE
Syntax Error in Website

### ISSUE THREAD

**Issue by silvanhi** [tidymodels/tune#366]
Hi Tidymodels Team

I believe there is a small syntax error in the article: https://tune.tidymodels.org/articles/extras/optimizations.html

You should use `doParallel:: `instead of `parallel::` in the code chunks. 

Best,
Silvan

**Comment by juliasilge** [comment]
I believe this is correct; the [parallel](https://stat.ethz.ch/R-manual/R-devel/library/parallel/html/detectCores.html) package has this function:

``` r
parallel::detectCores(logical = FALSE)
#> [1] 4
```

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The [doParallel](https://cran.r-project.org/package=doParallel) package does not:

``` r
doParallel::detectCores(logical = FALSE)
#> Error: 'detectCores' is not an exported object from 'namespace:doParallel'
```

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
