### ISSUE TITLE
Reduce data transfer overhead when tuning in parallel

### ISSUE THREAD

**Issue by klin333** [tidymodels/tune#376]
**Summary**: it seems all folds of cross validation are sent to every single parallel worker, even when each worker may only use 1 single fold, causing big unnecessary data transfer overhead. I'm new to this, so my understanding of the code could be wrong.

**Details**: In `tune:::tune_grid_loop()`, the potentially parallel `%op%` calls `tune:::tune_grid_loop_iter_safely()` with the full  `resamples` object as an function argument. This seems very odd, as for PSOCK workers, the entire `resamples` object (which is n folds bigger than the training data set) is sent to each and every worker, even though each worker may end up using only 1 of those folds. That's just based on my understanding of how parallel::\`%dopar%\` works but I haven't done any more tests.

Indicative current code from R/grid_code_paths.R `tune_grid_loop()`
```
results <- foreach::foreach(
  iteration = iterations,
  seed = seeds,
  .packages = packages,
  .errorhandling = "pass"
) %op% {
  tune_grid_loop_iter_safely(
    iteration = iteration,
    resamples = resamples,
    grid_info = grid_info,
    workflow = workflow,
    metrics = metrics,
    control = control,
    seed = seed
  )
```

Indicative change:
```
results <- foreach::foreach(
  split = resamples$splits,
  seed = seeds,
  .packages = packages,
  .errorhandling = "pass"
) %op% {
  tune_grid_loop_iter_safely(
    split = split,
    grid_info = grid_info,
    workflow = workflow,
    metrics = metrics,
    control = control,
    seed = seed
  )
```

**Comment by DavisVaughan** [comment]
I think this is a great point. We should definitely look into this. I think it should be possible to only send the data that is required to each worker

**Comment by topepo** [comment]
That would be good when `parallel_over = "resamples"` is used since we get one resample per worker

![](https://www.tmwr.org/figures/grid-logging-rs-1.svg)

When `parallel_over = "everything"`, each worker can have multiple resamples: 

![](https://www.tmwr.org/figures/grid-logging-all-1.svg)

**Comment by topepo** [comment]
> This seems very odd, as for PSOCK workers, the entire resamples object (which is n folds bigger than the training data set)

It does not make copies of the data in memory. 

``` r
library(rsample)
library(mlbench)

data(LetterRecognition)
lobstr::obj_size(LetterRecognition)
#> 2,644,640 B

set.seed(35222)
boots <- bootstraps(LetterRecognition, times = 50)
lobstr::obj_size(boots)
#> 6,686,776 B

# Object size per resample
lobstr::obj_size(boots)/nrow(boots)
#> 133,735.5 B

# Fold increase is <<< 50
as.numeric(lobstr::obj_size(boots)/lobstr::obj_size(LetterRecognition))
#> [1] 2.528426
```

<sup>Created on 2021-06-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

With your approach, we would save on the cost of the integers that define the rows in the analysis set though.

**Comment by klin333** [comment]
> It does not make copies of the data in memory.
> 
> With your approach, we would save on the cost of the integers that define the rows in the analysis set though.

Arh, I didn’t check for single machine. I was referring to the case where the psock slaves are on other remote machines, for which case I’m quite sure all the folds get sent to all remote workers.

Also, for Windows, not sure if memory copies are made or not when slaves are on the same machine, might test when I get a chance.

**Comment by topepo** [comment]
We checked today and PSOCK serializes the data. You are right;  the full size is used. The workers are running Windows?

**Comment by klin333** [comment]
> We checked today and PSOCK serializes the data. You are right; the full size is used. The workers are running Windows?

Yes, master and slaves are all running Windows across all machines when I checked.

**Comment by klin333** [comment]
> When `parallel_over = "everything"`, each worker can have multiple resamples:

I see your point. With `parallel_over = "everything"`, solving this issue will only reduce data transfer overhead if the `parallel_over = "everything"` is changed such each fold gets distributed to the minimum number of workers. Eg in you example of 7 models 5 folds and 10 worker cores, fold1 only goes to say cores 1&2 where core 1 runs 3 models and core2 runs 4 models; fold2 only goes to cores 3&4, etc. This would also reduce the number of repetitions the preprocessing step is run. This is probably a more general discussion of `parallel_over`... 

Also not sure if I'm just misunderstanding it, but I think your diagram of the `parallel_over = "everything"` should show the tasks within each worker (which I assume to be 1 core) running one after the after, as opposed to what appears to be running in parallel within the one core.
