### ISSUE TITLE
Add alt text to `autoplot` methods

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/tune#380]
To improve accessibility, we can add `alt` labels to the output of the `autoplot` methods.

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip

set.seed(6735)
folds <- vfold_cv(mtcars, v = 5)

spline_rec <-
  recipe(mpg ~ ., data = mtcars) %>%
  step_ns(disp, deg_free = tune("disp")) %>%
  step_ns(wt, deg_free = tune("wt"))

lin_mod <-
  linear_reg() %>%
  set_engine("lm")

spline_grid <- crossing(disp = 2:5, wt = 2:5)

spline_res <-
  tune_grid(lin_mod, spline_rec, resamples = folds, grid = spline_grid)

autoplot(spline_res) +
  labs(
    alt = paste0("Tuning results with small multiples showing two metrics:", 
                 "RMSE and R squared. The x-axis displays disp, ",
                 "the y-axis displays mean metric value over the resamples, ",
                 "and color displays wt.")
  )
```

![](https://i.imgur.com/r95cgsO.png)

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This is just one initial idea of what to include and how to include it; we can do [more learning about how to write alt text](https://moz.com/learn/seo/alt-text) for this context.

**Comment by simonpcouch** [comment]
Glad that you filed this issue—thank you. In light of our learnings in the last couple years, lets move forward with [writing alt text image-by-image in favor of automated alt text](https://www.a11yproject.com/posts/alternate-text-and-automation/). Closing in favor of #748.
