### ISSUE TITLE
`last_fit` requires `rsample::initial_split()` object. But it's not compatible with `rsample::sliding_window()` or the other two similar methods.

### ISSUE THREAD

**Issue by PathosEthosLogos** [tidymodels/tune#400]
I couldn't find anything in the documentation about this, so I thought I would request this feature. It would be nice if the `sliding_window` arguments would be `tune()`-able so that it finds the best fit with `last_fit`.

Is there an alternative or a solution? I'm curious what others have tried.

**Comment by DavisVaughan** [comment]
We currently have no plans to make rsample arguments tunable
