### ISSUE TITLE
Wrong link on extract_model page

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/tune#407]
On 
- https://tune.tidymodels.org/reference/extract_model.html 
- https://tune.tidymodels.org/dev/reference/extract-tune.html
- https://tune.tidymodels.org/dev/reference/fit_resamples.html
- https://tune.tidymodels.org/dev/reference/reexports.html
- https://tune.tidymodels.org/dev/reference/tune_bayes.html
- https://tune.tidymodels.org/dev/reference/tune_grid.html

The `extract_*fit_engine*()` links to https://rdrr.io/cran/hardhat/man/hardhat-extract.html but should link to https://tune.tidymodels.org/reference/extract-tune.html

**Comment by EmilHvitfeldt** [comment]
`hardhat::mold()` also directs wrong here:
https://tune.tidymodels.org/dev/reference/extract-tune.html

**Comment by juliasilge** [comment]
I guess we could use `extract_fit_engine.tune_results` instead to link to the method? I've had people say that is confusing to them to see the method in docs like that, though. Maybe we could use [links](https://roxygen2.r-lib.org/articles/rd-formatting.html#links-2) to do something like:

```r
[`extract_fit_engine()`][extract_fit_engine.tune_results()]
```
