### ISSUE TITLE
Better SEO for options(tidymodels.dark = TRUE)

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/tune#417]
I can never remember how to turn on this setting, and the results from searching "tidymodels dark mode" lead to the documentation for [control_grid](https://tune.tidymodels.org/reference/control_grid.html) as a comment in the documentation for the `verbose` argument. Would it be possible to have this documented in a different way to make it cleaner and easier to find when searching the web?

I don't know if this is the right repo for this question.

**Comment by juliasilge** [comment]
If we move to using cli more (as outlined in #138) then we [likely will not want](https://cli.r-lib.org/reference/builtin_theme.html) to use `tidymodels.dark` anymore, since it has good support for detecting and supporting dark themes.
