### ISSUE TITLE
tune logo: green or grey text?

### ISSUE THREAD

**Issue by hfrick** [tidymodels/tune#419]
The [logo in the repo](https://github.com/tidymodels/tune/blob/master/man/figures/logo.png) has grey text and is from December 2019. 

The [logo in the hex-sticker repo](https://github.com/rstudio/hex-stickers/blob/master/PNG/tune.png) has green text and is from April 2020.

Should the logo here be updated to the green version?

**Comment by juliasilge** [comment]
Yes, I believe we got it updated but never updated it here in the repo. 🙈 It should be the one in the `/rstudio/hex-stickers`.
