### ISSUE TITLE
 Image loading error in the documentation of the Acquisition Functions

### ISSUE THREAD

**Issue by rafzamb** [tidymodels/tune#428]
HI, when reviewing the documentation of the vignettes of "Acquisition Functions", some images are not displayed.
https://tune.tidymodels.org/articles/acquisition_functions.html

**Comment by juliasilge** [comment]
Yep, we have fixed this in the dev version of the site here:
https://tune.tidymodels.org/dev/articles/acquisition_functions.html

That will show up on the release site the next time we do a CRAN release. Thanks for the report!
