### ISSUE TITLE
Controlling metric event_level for last_fit()

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/tune#431]
## The problem

Hi,

Maybe I'm missing something, but how does `last_fit.workflow` know which `event_level` to use for metric computations? All other fitting functions allow the user to specify this via `control` argument, but this function defines the controller inside the function itself (see below) via `control_resamples()`. `control_resamples()` has `event_level = 'first'` by default, yet when I use `last_fit()` it returns the metrics for `event_level = 'second'`, which is actually what I want. I am just not sure where `last_fit` is inheriting this behaviour.

https://github.com/tidymodels/tune/blob/6897071ff1201e333692db890b87bbc909a46706/R/last_fit.R#L103-L108

## Reprex

``` r
library(tidymodels)

data <- mutate(mtcars, vs = factor(vs))

tt_split <- initial_split(data, prop = 8/10, strata = 'vs')
rs <- bootstraps(training(tt_split), times = 1, strata = 'vs')

wflow <-
  workflow() %>%
  add_model(
    logistic_reg(penalty = tune(), mixture = tune()) %>%
      set_engine('glmnet')
  ) %>%
  add_formula(vs ~ .)

results <- tune_grid(
  wflow,
  resamples = rs,
  grid = 1,
  control = control_grid(event_level = 'second')
)

show_best(results, metric = 'roc_auc')
#> # A tibble: 1 × 8
#>    penalty mixture .metric .estimator  mean     n std_err .config             
#>      <dbl>   <dbl> <chr>   <chr>      <dbl> <int>   <dbl> <chr>               
#> 1 0.000227   0.749 roc_auc binary      0.95     1      NA Preprocessor1_Model1

finalize_workflow(
  wflow,
  select_best(results, metric = 'roc_auc')
) %>%
  last_fit(tt_split) %>%
  collect_metrics()
#> # A tibble: 2 × 4
#>   .metric  .estimator .estimate .config             
#>   <chr>    <chr>          <dbl> <chr>               
#> 1 accuracy binary             1 Preprocessor1_Model1
#> 2 roc_auc  binary             1 Preprocessor1_Model1
```

**Comment by juliasilge** [comment]
I believe this is the same as #399 but let me know if I am mistaken

**Comment by mattwarkentin** [comment]
Indeed this looks like a duplicate issue. On the plus side, I'm glad I wasn't missing something obvious; on the down side, my searching skills could be better.
