### ISSUE TITLE
add a notes column

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#44]
catalog warnings and errors here (and other stuff). When parallel process, no output comes back and if something goes wrong all you get is a message that "all models failed" (there was details in output but it fails to show).

**Comment by jonthegeek** [comment]
In both #59 and #60, the error is a missing package, but it takes some jumps to find that. For #59, it was the call to `foreach::foreach` in `tune_rec_and_mod`, hiding `<simpleError: These packages could not be loaded: 'kknn'>`. 

It looks like it's pretty much the same in #60, so maybe add a helper that checks for package-load issues in the foreach calls (either by wrapping foreach::foreach or maybe by providing a .combine function)?
