### ISSUE TITLE
remove `required_pkgs.model_spec()`

### ISSUE THREAD

**Issue by hfrick** [tidymodels/tune#440]
The method currently exists in [parsnip](https://github.com/tidymodels/parsnip/blob/main/R/req_pkgs.R#L56-L59)  and [tune](https://github.com/tidymodels/tune/blob/696ef36f582937b34038febeaa315c206122e0a3/R/load_ns.R#L69-L86) so loading tidymodels always gives a note about that.

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
```

<sup>Created on 2021-11-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by topepo** [comment]
Do we need both `required_pkgs` _and_ `req_pkgs`?

**Comment by EmilHvitfeldt** [comment]
In {parsnip}, `req_pkgs()` is used to inside `required_pkgs()`, and In a couple of tests. I think it would be safe to rewrite `required_pkgs()` to not use it, and start the deprecation of `req_pkgs()`.

Just to be clear, we want to remove `required_pkgs.model_spec()` from {tune} and only have it in {parsnip} right?
