### ISSUE TITLE
Uninformative error if wrong `control_*()` is used

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/tune#449]
See reprex below. This should be a fairly easy since since the control functions return specific classes we can check against.

``` r
library(tidymodels)

rec_no_tune_1 <-
  recipe(mpg ~ ., data = mtcars) %>%
  step_normalize(all_predictors())

set.seed(363)
mt_folds <- vfold_cv(mtcars, v = 5)

glmn_mod <- decision_tree(tree_depth = tune(), min_n = 2) %>% 
  set_mode("regression") %>%
  set_engine("rpart")

workflow() %>%
  add_recipe(rec_no_tune_1) %>%
  add_model(glmn_mod) %>%
  tune_bayes(mt_folds, control = control_grid())
#> Error in if (is.na(limit)) {: argument is of length zero
```

<sup>Created on 2022-02-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by topepo** [comment]
In iterative tuning methods and racing, we pass a single control function for the function (e.g. `tune_sim_anneal()`) and that is used to work with another function, usually `tune_grid()`. 

I think that we need a set of `as_control_grid()` methods that will convert from one control type to another. We’d need these to go from more complete methods to less complex. For example, we would need `as_control_resamples.control_grid()` but not `as_control_grid.control_resamples()`.
