### ISSUE TITLE
[FR] last_fit() should use your exact penalty value when fitting glmnet model

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/tune#458]
Hi,

I should start by saying I am aware of the very good reasons why `glmnet::glmnet()` prefers to fit entire regularization paths rather than single lambdas; and also that even if *your* lambda isn't one of the lambdas in the path, you can still get coefficients and predictions at your lambda via interpolation. I think this is more than satisfactory for hyperparameter tuning and cross-validation given that you only need to fit a single `glmnet()` model to test the performance of many penalty values (i.e. submodels) so it is very efficient.

However, I think that `last_fit()` should fit a `glmnet` model that includes your chosen `penalty` value in the regularization path so that you get **exact** coefficients and predictions rather than interpolated ones for this final `penalty` value.

This could be done by passing in a manual sequence of lambdas that includes your chosen lambda squeezed somewhere in the middle. It would probably require `last_fit_workflow()` to add a flag to the `object` indicating this is the "final" fit (e.g. `object$is_last_fit <- TRUE`) rather than a normal fit, and then a little condition handling in the `glmnet` fitting functions in `parsnip`.

https://github.com/tidymodels/tune/blob/d063189185d4bc976c044614333d69290c6707a0/R/last_fit.R#L114-L120

What do you think about this proposal?

Relevant: From the `glmnet` documentation: 
> ...the predict function uses linear interpolation to make predictions for values of s (lambda) that do not coincide with those used in the fitting algorithm. While this is often a good approximation, it can sometimes be a bit coarse.

**Comment by mattwarkentin** [comment]
Thanks for the response, @topepo. I was unaware of the `path_values` argument.

Could you clarify this point from that vignette?

> For example, we have found that if you want a fully ridge regression model (i.e., mixture = 0), you can get the wrong coefficients if the path does not contain zero (see [issue #431](https://github.com/tidymodels/parsnip/issues/431#issuecomment-782883848)).

Does this mean that you could get the wrong coefficients for a purely ridge model (`mixture/alpha = 0`) even if the penalty of interest is > zero? Why does adding zero to the regularization path have this effect? Maybe I'm misunderstanding even after reading the linked issue.

**Comment by topepo** [comment]
> Does this mean that you could get the wrong coefficients for a purely ridge model (mixture/alpha = 0) even if the penalty of interest is > zero? 

Yes. We don't really know why but I assume that it has no left-hand value to use for a linear approximation between 0 and `min(lambda)`. ¯\\_(ツ)_/¯ The remarks in that issue are from one of the maintainers of that package. I try to always add zero to the path.
