### ISSUE TITLE
issue template proposal

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#47]
# Making a new issue for `tune`

Please follow the template below. 

If the question is related at all to a specific data analysis, please include a **minimal reprex** (reproducible example). If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

Tips: 

 * Here is a good example issue: [#46](https://github.com/topepo/tune/issues/46)
 
 * **Issues without a reprex will have a lower priority than the others.** 

 * We don't want you to use confidential data; you can blind the data or simulate other data to demonstrate the issue. The functions [`caret::twoClassSim()`](https://www.rdocumentation.org/packages/caret/versions/6.0-84/topics/SLC14_1) or [`caret::SLC14_1()`](https://www.rdocumentation.org/packages/caret/versions/6.0-84/topics/SLC14_1) might be good tools to simulate data for you. 

 * Unless the problem is explicitly about parallel processing, please run sequentially. 

   * Even if it about parallel processing, please make sure that it runs sequentially first.

 * Make liberal use of `set.seed()` to help reproducibility 

 * Please check <https://stackoverflow.com/> or <https://community.rstudio.com/> to see if someone has already asked the same question (see: [Yihui's Rule](https://yihui.name/en/2017/08/so-gh-email/)). 

 * You might need to install these:

```r
install.packages(c("reprex", "sessioninfo"), repos = "http://cran.r-project.org")
```

<br>

When are ready to file the issue, please delete the parts above this line:
< -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

## The problem

I'm having trouble with ... or 

Have you considered ... 

## Reproducible example

Copy your code to the clipboard and run:

```r
reprex::reprex(si = TRUE)
```

**Comment by topepo** [comment]
Feedback from @batpigandme and @hadley would be helpful too.

**Comment by hadley** [comment]
I don't think it's worth putting much effort into this since evidence suggests that people don't read issue templates.

**Comment by batpigandme** [comment]
Sorry, @topepo, I must have imagined giving feedback. I agree that, in practice, people tend to ignore the templates, but it can't hurt to have one. The only thing I would add would be to explicitly state that they should give expected output in problem description. It won't always be relevant, but it's the one of the things that makes so many questions on community incomprehensible.

**Comment by batpigandme** [comment]
You're right, @topepo, our setup for the other repos uses the "outdated" version described here:
https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository

Now they want the issue templates to be a dropdown, but if we use the "old-workflow" setup the issues are automatically populated (e.g. https://github.com/tidyverse/dplyr/blob/master/.github/ISSUE_TEMPLATE.md automatically populates all issues in dplyr).
