### ISSUE TITLE
Support a model_stack from stacks with last_fit

### ISSUE THREAD

**Issue by py9mrg** [tidymodels/tune#470]
## Feature

Not sure if this is best posted here or on the stacks github, but...

Can we please have a `last_fit.model_stack` so that we can use `last_fit` with `stacks`? Currently we have to do it manually which, while not difficult, it would be nice to use `last_fit` with a model stack as well.

**Comment by topepo** [comment]
A stacked ensemble uses out-of-sample predictions to create the ensemble. If you use the test set, you have no method for determining if the ensemble is working. Also, you would be evaluating numerous models on the test set and that's problematic. 

I don't think that this is a great idea so we won't be making any changes. 

Perhaps it would be better to use a validation set as the input into the data stack? You can use `validation_split()` to achieve this.
