### ISSUE TITLE
404 Error on Bayesian Optimization of Classification Model article

### ISSUE THREAD

**Issue by tmastny** [tidymodels/tune#51]
On the website, I get a 404 Page Not Found error when I click on the Bayesian Optimization of Classification Model article:
https://tidymodels.github.io/tune/articles/extras/articles/extras/classification.html

**Comment by topepo** [comment]
Hmm.  After changing the name,. I regenerated the `pkgdown` files to have the right name. Local files are good but GH checks them in with the uppercase names ¯\_(ツ)_/¯

I missed the links in the README file to :-(

I'll do the same again with a different file name.

**Comment by topepo** [comment]
Good now
