### ISSUE TITLE
last_fit() taking training and testing data as arguments

### ISSUE THREAD

**Issue by PursuitOfDataScience** [tidymodels/tune#559]
Hi,

Instead of just providing an `initial_split()` object as the argument, is it possible to specify the training and testing data as two separate arguments? Sometimes, the training data after the initial split needs to be tweaked to be several different versions of training data. In this case, it wouldn't be convenient to use `last_fit()` at all. 

Thanks!

**Comment by topepo** [comment]
I think the solution is to make a new split object using [`manual_split()`](https://rsample.tidymodels.org/reference/manual_rset.html). Either that or just use a few lines of `fit()` and `predict()` to get the same results.

**Comment by PursuitOfDataScience** [comment]
Thanks for pointing this out. Didn't know this before asking the question. I thought `initial_split()` was the only solution.
