### ISSUE TITLE
by can't contain join column id

### ISSUE THREAD

**Issue by ymer** [tidymodels/tune#56]
## The problem

I'm having trouble with running a simple random forest tuning.

## Reproducible example

```
library(tidymodels)
library(tune)
set.seed(1)

df <- tibble(
  x1 = runif(1000, 5, 10),
  x2 = runif(1000, 20, 30),
  outcome = as.factor(ifelse(x1 + x2 > 32, 1, 0))
)

rec <- recipe(df, outcome ~ .)
rf_mod <- rand_forest(mode = "classification", trees = tune()) %>% 
  set_engine("randomForest")
cv_splits <- vfold_cv(df, v = 4)
grid <- expand.grid(trees = c(100, 200))

tune_grid(rec, model = rf_mod, rs = cv_splits, grid = grid)
```

#> `by` can't contain join column `id` which is missing from RHS

**Comment by topepo** [comment]
Thanks for finding this. I'll fix it tonight. 

In the future, can you please follow the posting guide to use `reprex::reprex(si = TRUE)` so that we see the execution and get version info?
