### ISSUE TITLE
parallel processing

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#6]
For now, this should probably work for the outer resampling grid. 

For `tune_rec()` and `tune_mod()`, we might be able to collapse the resampling and parameter loops but this should wait until post-processing is worked out. 

We should also _disable_ parallel processing if any `engine = "keras"`. 

Also also, there should be a control option to opt-out of parallel processing even if it is available.

**Comment by jaredlander** [comment]
Since Bayesian optimization can't be done in parallel it would be nice for models like `xgboost` to be fit in parallel (perhaps even on a GPU). So for packages where parallel is disabled, can their internal fitting be done in parallel when using `tune_bayes()`?

**Comment by topepo** [comment]
It does the resampling in parallel currently. So the initial set, if generated by the function, is done in parallel and each new candidate set is resampled in parallel. 

If you want to use `xgboosts`'s parallelism, don't use `foreeach` and pass the `nthread` option via `set_engine()`.

**Comment by jaredlander** [comment]
That makes sense. I meant using `nthread` not `foreach`. If I set `nthread` will that create issues for the parallel resampling.
