### ISSUE TITLE
Suggestion: Why can I only set it with mean() of metric calculated for each folder?

### ISSUE THREAD

**Issue by SHo-JANG** [tidymodels/tune#638]
Sometimes I want to select parameters based on median or minmax statistics, not mean. Is there a reason why the function is fixed to mean?

**Comment by simonpcouch** [comment]
Thanks for the issue! Note that `collect_metrics` has a `summarize` argument that defaults to `TRUE`, in which case estimates are summarized by the mean. However, setting `summarize = FALSE` will allow you to use whatever summary function you wish:

``` r
library(tidymodels)
library(testthat)

res <- fit_resamples(linear_reg(), mpg ~ ., bootstraps(mtcars))

# by default, mean metrics are supplied per metric/estimator
collect_metrics(res)
#> # A tibble: 2 × 6
#>   .metric .estimator  mean     n std_err .config             
#>   <chr>   <chr>      <dbl> <int>   <dbl> <chr>               
#> 1 rmse    standard   4.27     25  0.298  Preprocessor1_Model1
#> 2 rsq     standard   0.693    25  0.0344 Preprocessor1_Model1

# `summarize = TRUE` results can be recreated with dplyr
expect_equal(
  collect_metrics(res) %>% pull(mean),
  collect_metrics(res, summarize = FALSE) %>% 
    group_by(.metric, .estimator) %>%
    summarize(mean = mean(.estimate), .groups = "drop") %>%
    pull(mean)
)

# to use a different summary function, pass `summarize = FALSE`
collect_metrics(res, summarize = FALSE) %>% 
  group_by(.metric, .estimator) %>%
  summarize(median = median(.estimate), .groups = "drop")
#> # A tibble: 2 × 3
#>   .metric .estimator median
#>   <chr>   <chr>       <dbl>
#> 1 rmse    standard    3.72 
#> 2 rsq     standard    0.772
```

<sup>Created on 2023-03-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SHo-JANG** [comment]
Wow.. I did't know this option! 
But how can I apply this in tuning process?  (tune_bayes , annealing...)

**Comment by simonpcouch** [comment]
To evaluate with another metric summarization function after evaluating over resamples, use `collect_metrics(summarize = FALSE)` as above. To control elements of the tuning process for iterative tuning functions like `tune_bayes()`, `tune_sim_anneal()`, etc, see the documentation for analogous `control_*()` functions.
