### ISSUE TITLE
getting installation error

### ISSUE THREAD

**Issue by fahadshery** [tidymodels/tune#66]
Hi,

trying to install `tune` 

```r
devtools::install_github("tidymodels/tune")
```
This then asks:

```r
These packages have more recent versions available.
Which would you like to update?

1: All                                          
2: CRAN packages only                           
3: None                                         
4: parsnip (0.0.3.9001 -> ae42617a9...) [GitHub]
5: cli     (1.1.0      -> ad6410aee...) [GitHub]

Enter one or more numbers, or an empty line to skip updates:
1
parsnip   (0.0.3.9001 -> ae42617a9...) [GitHub]
cli       (1.1.0      -> ad6410aee...) [GitHub]
backports (NA         -> 1.1.5       ) [CRAN]
```

Getting the error:

```r
Error: Failed to install 'tune' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘backports’

```

**Comment by topepo** [comment]
Can you follow the template and provide the session info?

**Comment by fahadshery** [comment]
Hi,

thanks for your prompt response. I manually installed the `backports` package. But now getting the following error:

```r
library(tune)
Error: package or namespace load failed for ‘tune’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘cli’ 1.1.0 is being loaded, but >= 1.9.9.9000 is required
```

Here is the `session_info`

```r
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] recipes_0.1.7 dplyr_0.8.3   ggplot2_3.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         pillar_1.4.2       compiler_3.6.1     gower_0.2.1        lhs_1.0.1          class_7.3-15      
 [7] tools_3.6.1        rpart_4.1-15       packrat_0.5.0      ipred_0.9-9        lubridate_1.7.4    tibble_2.1.3      
[13] gtable_0.3.0       lattice_0.20-38    pkgconfig_2.0.3    rlang_0.4.0        Matrix_1.2-17      rstudioapi_0.10   
[19] prodlim_2018.04.18 stringr_1.4.0      withr_2.1.2        generics_0.0.2     grid_3.6.1         nnet_7.3-12       
[25] tidyselect_0.2.5   glue_1.3.1         R6_2.4.0           survival_2.44-1.1  lava_1.6.6         purrr_0.3.2       
[31] magrittr_1.5       scales_1.0.0       MASS_7.3-51.4      splines_3.6.1      GPfit_1.0-8        assertthat_0.2.1  
[37] timeDate_3043.102  colorspace_1.4-1   stringi_1.4.3      lazyeval_0.2.2     munsell_0.5.0      crayon_1.3.4      
```

**Comment by fahadshery** [comment]
just resolved it by:

```
1- restart Rstudio
2- install cli from github (install_github("r-lib/cli"))
3- reload tune
```

**Comment by topepo** [comment]
Thanks for the additional info. 

It's unexpected that you had that error since we have it setup to download the development version of `cli`. Do you remember what code that you used to install the package?

**Comment by fahadshery** [comment]
tune package was installed using:

```r
devtools::install_github("tidymodels/tune")
```

this produced `backports` issue. I simply reinstalled `backports`.

After this re-ran:

```r
devtools::install_github("tidymodels/tune")
```

and it installed the tune and compiled fine but gave the `cli` error. I was struggling to detach it but had to restart rstudio.

after restarting then ran:

```r
devtools::install_github("r-lib/cli")
```

all worked fine

**Comment by topepo** [comment]
Thanks for the information!

**Comment by rodfloripa** [comment]
I have the same problem:

Downloading GitHub repo tidymodels/tune@HEAD
Rcpp      (1.0.1   -> 1.0.6 ) [CRAN]
crayon    (1.3.4   -> 1.4.1 ) [CRAN]
digest    (0.6.18  -> 0.6.27) [CRAN]
tibble    (3.0.6   -> 3.1.0 ) [CRAN]
ps        (1.5.0   -> 1.6.0 ) [CRAN]
pkgload   (1.1.0   -> 1.2.0 ) [CRAN]
jsonlite  (1.6     -> 1.7.2 ) [CRAN]
evaluate  (0.13    -> 0.14  ) [CRAN]
farver    (2.0.3   -> 2.1.0 ) [CRAN]
lubridate (1.7.9.2 -> 1.7.10) [CRAN]
Installing 10 packages: Rcpp, crayon, digest, tibble, ps, pkgload, jsonlite, evaluate, farver, lubridate

  There are binary versions available but the source versions are later:
           binary source needs_compilation
tibble      3.0.6  3.1.0              TRUE
ps          1.5.0  1.6.0              TRUE
pkgload     1.1.0  1.2.0              TRUE
farver      2.0.3  2.1.0              TRUE
lubridate 1.7.9.2 1.7.10              TRUE

Error: Failed to install 'tune' from GitHub:
  (convertido do aviso) package 'jsonlite' is in use and will not be installed
Traceback:

1. devtools::install_github("tidymodels/tune")
2. pkgbuild::with_build_tools({
 .     ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
 .         rlang::warn))
 .     {
 .         remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
 .             auth_token = auth_token, host = host)
 .         install_remotes(remotes, auth_token = auth_token, host = host, 
 .             dependencies = dependencies, upgrade = upgrade, force = force, 
 .             quiet = quiet, build = build, build_opts = build_opts, 
 .             build_manual = build_manual, build_vignettes = build_vignettes, 
 .             repos = repos, type = type, ...)
 .     }
 . }, required = FALSE)
3. withr::with_path(rtools_path(), code)
4. force(code)
5. install_remotes(remotes, auth_token = auth_token, host = host, 
 .     dependencies = dependencies, upgrade = upgrade, force = force, 
 .     quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
 .     build_vignettes = build_vignettes, repos = repos, type = type, 
 .     ...)
6. tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
 .     stop(remote_install_error(remotes[[i]], e))
 . })
7. tryCatchList(expr, classes, parentenv, handlers)
8. tryCatchOne(expr, names, parentenv, handlers[[1L]])
9. value[[3L]](cond)

**Comment by DavisVaughan** [comment]
> (convertido do aviso) package 'jsonlite' is in use and will not be installed

it looks like you need to restart R, try installing jsonlite by itself, restart R again, then try reinstalling tune again. you may have to do this a few times for other packages as well
