### ISSUE TITLE
there should be a method of getting best estimator and best score

### ISSUE THREAD

**Issue by fahadshery** [tidymodels/tune#70]
As we do tunning like `Bayesian hyper-parameter tuning` or a simple `grid search`, there should be a method to get the best `tuned estimates` e.g.

```r
# define model_spec
spec_xgboost <- boost_tree(mode = "classification", 
                           tree_depth = tune(),
                           trees = tune(),
                           learn_rate = tune(),
                           mtry = tune(),
                           min_n = tune()) %>% set_engine("xgboost")

## The workflow should have a recipe or a formula attached to it.
xgb_wf <- workflow() %>%
            add_model(spec_xgboost) %>%
          add_formula(Class ~ .)

# final grid
grid <- xgb_wf %>%
  param_set() %>%
  update(mtry = mtry(c(1,20)))%>%
  grid_max_entropy(size = 20)

grid_results <- tune_grid(xgb_wf, rs = folds, grid = grid,
                          perf = metric_set(roc_auc),
                          control = grid_control(verbose = TRUE))

get_best_score(grid_results)
get_best_params(grid_results)

tb_results <- tune_Bayes(ames_wflow,rs = cv_splits,initial = initial_grid,perf = metric_set(rmse),
                   objective = exp_improve(foo),
                   iter = 20,
                   control = Bayes_control(verbose = TRUE,uncertain = 10,extract = num_leaves))

get_best_score(tb_results)
get_best_params(tb_results)
```

I called it `get_best_params()` and `get_best_score()`. These set of `best estimate params` should then could be directly passed to the `model fit` to build the `final model`

apologies if its already being implemented. 

Regards,

**Comment by topepo** [comment]
See #12.

Feel free to make a PR though. If you do, I would combine your two functions and 

* make sure that you return a tibble is a single row
* add a `performance = TRUE` option to also have columns for the corresponding performance estimates
* have a `maximize` argument. We'll be able to automate this later but will need an argument in the short term
* maybe call it `select_best()`

**Comment by fahadshery** [comment]
i am working on it but I can't seem to access `summarise.tune_results` method from `tune`. For example: `tune:::summarise.tune_results(x)` gives error:

```r
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'summarise.tune_results' not found
```

how do I reuse this method?

**Comment by fahadshery** [comment]
just submitted my first ever PR. please be gentle :D
