### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#77]
For the messages/symbols that are produced, have an option for uses who use a dark mode in their terminal/IDE

**Comment by jaredlander** [comment]
I assume this refers to the hard to read printing of messages? I find it very hard to read in dark mode. Also, at least on my Windows setup, the checkmark shows as <U+2713>.

![image](https://user-images.githubusercontent.com/628977/67737902-2bd85100-f9e3-11e9-8459-5d78ec29a765.png)

**Comment by topepo** [comment]
Affirmative
