### ISSUE TITLE
add Brier score to default classification metrics

### ISSUE THREAD

**Issue by topepo** [tidymodels/tune#779]
We'll have to regenerate the cached example objects used for testing and demo;ing.

**Comment by PathosEthosLogos** [comment]
>We'll have to regenerate the cached example objects used for testing and demo;ing.

@topepo maybe I'm unclear on what you mean by 'default' but Brier score is working well. Do you mean that it should be default for multinomial outputs without explicit specification?

**Comment by EmilHvitfeldt** [comment]
Hello @PathosEthosLogos, it means that, right now if you don't specify anything to the `metrics` argument of `tune_grid()` it picks ` yardstick::metric_set(roc_auc, accuracy)` https://github.com/tidymodels/tune/blob/59057d29d455ed4818f94a562a5ae4d0ab7004f0/R/metric-selection.R#L208, the idea is to add `brier_class()` to that list

**Comment by EmilHvitfeldt** [comment]
Maybe we should remove some code duplication:

https://github.com/tidymodels/tune/blob/59057d29d455ed4818f94a562a5ae4d0ab7004f0/R/checks.R#L345-L363

https://github.com/tidymodels/tune/blob/59057d29d455ed4818f94a562a5ae4d0ab7004f0/R/metric-selection.R#L202-L218
