### ISSUE TITLE
Ability to tune multiple models

### ISSUE THREAD

**Issue by jaredlander** [tidymodels/tune#81]
Feature Request:

The `model()` function in `{fable}` allows fitting multiple models to the data. Would be great if we could tune over multiple models, either in the same vein like C5 and xgboost, or accross different types like glmnet and xgboost.

Maybe this is more appropriate in workflows, but `{tune}` is what sparked the idea for me.

**Comment by topepo** [comment]
That's been asked somewhere else too. It shouldn't be difficult to do but we need to get the fundamental stuff done first. Also, I think that this would apply just to grid search?

**Comment by jaredlander** [comment]
Pretty sure I'm the one who asked you somewhere else and you said make an issue.

A random search too, but I guess you mean that when you say grid.

**Comment by juliasilge** [comment]
This functionality is now available in the [workflowsets](https://workflowsets.tidymodels.org/) package! 🎉
