### ISSUE TITLE
Tuning censored models on large data generated variable names >10000 bytes

### ISSUE THREAD

**Issue by joranE** [tidymodels/tune#824]
I was following the example code for tuning censored models from [this issue](https://github.com/tidymodels/censored/issues/296) that @hfrick so helpfully provided, using the development versions of the packages used in that example.

However, when I tried it on my own data, which is considerably larger than the lung data set, I immediately got errors about variable names being generated that are over 10k bytes long, as shown in the reprex below.
``` r
# install dev versions
pak::pak(
  paste0("tidymodels/", c("parsnip", "censored", "workflows", "yardstick", "tune"))
)

library(tidyverse)
library(tidymodels)
library(censored)
#> Loading required package: survival

lung <- as_tibble(survival::lung) |> 
  drop_na()

# Make the lung data set very big
lung <- lung[sample(nrow(lung),size = 10000,replace = TRUE),]

lung_train <- lung[-c(1:5), ]
lung_test <- lung[1:5, ]

# Create cross-validation data from training data
set.seed(0)
folds <- vfold_cv(lung_train, v = 5)

# Define a decision tree with cost complexity set for tuning
dt_spec <- 
  decision_tree(cost_complexity = tune()) %>%
  set_engine("rpart") %>% 
  set_mode("censored regression") 
dt_spec
#> Decision Tree Model Specification (censored regression)
#> 
#> Main Arguments:
#>   cost_complexity = tune()
#> 
#> Computational engine: rpart

# Try to tune the specified model
set.seed(0)
dt_grid <- tune_grid(
  dt_spec, 
  Surv(time, status) ~ .,
  folds,
  grid = 2,
  eval_time = 100
)
#> → A | error:   variable names are limited to 10000 bytes
#> There were issues with some computations   A: x1
#> There were issues with some computations   A: x2
#> 
#> → B | error:   Cannot find current progress bar for `<environment: 0x15229b4d8>`
#> Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
#> information.
#> Warning: More than one set of outcomes were used when tuning. This should never
#> happen. Review how the outcome is specified in your model.
```

<sup>Created on 2024-01-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

After much digging, I think the issue is occurring `prodlim:::predictList`, specifically here:

```
names.strata <- apply(do.call("cbind", lapply(names(requested.X), 
            function(n) {
                if (is.numeric(requested.X[, n])) 
                  paste(n, format(requested.X[, n], digits = 2), 
                    sep = "=")
                else paste(n, requested.X[, n], sep = "=")
            })), 1, paste, collapse = ", ")
```

...as it appears to be generating column names by collapsing together an exceedingly long set of new data values.

**Comment by simonpcouch** [comment]
A reprex with "just" censored:

``` r
library(tidymodels)
library(censored)
#> Loading required package: survival
library(pec)
#> Loading required package: prodlim

lung <- as_tibble(survival::lung) |>
  drop_na()

lung <- lung[sample(nrow(lung),size = 10000,replace = TRUE),]

lung_train <- lung[-c(1:5000), ]
lung_test <- lung[1:5000, ]

set.seed(0)
folds <- vfold_cv(lung_train, v = 5)

dt_spec <- decision_tree() %>%
  set_engine("rpart") %>%
  set_mode("censored regression")

m <- fit(dt_spec, formula = Surv(time, status) ~ ., lung_train)
predict(m, lung_test, type = "survival", eval_time = 100)
#> Error in do.call("rbind", psurv): variable names are limited to 10000 bytes
```

<sup>Created on 2024-01-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by hfrick** [comment]
Ah, it's the high number of observations in the test set that make the predictions choke - but not just in censored. this is also the case for the underlying engine package, pec:

``` r
library(tidymodels)
library(censored)
#> Loading required package: survival
library(pec)
#> Loading required package: prodlim

lung <- as_tibble(survival::lung) |>
  drop_na()

lung <- lung[sample(nrow(lung),size = 10000,replace = TRUE),]

lung_train <- lung[-c(1:5000), ]
lung_test <- lung[1:5000, ]

engine_fit <- pec::pecRpart(Surv(time, status) ~ ., data = lung_train)
pec::predictSurvProb(engine_fit, newdata = lung_test, times = 100)
#> Error in do.call("rbind", psurv): variable names are limited to 10000 bytes
```

<sup>Created on 2024-01-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hfrick** [comment]
Or more precisely, {prodlim} rather than {pec} - which is also where @joranE landed. 

@joranE Do you want to report your findings to the prodlim maintainer or should we? 

I think this is not a censored/tidymodels issue so I'll close this issue here.

**Comment by joranE** [comment]
Thanks for following up @hfrick @simonpcouch ! Sorry for the noise, as yeah, this is pretty clearly a prodlim issue. I just didn't dig super hard when I saw that the prodlim [CRAN page](https://cran.r-project.org/web/packages/prodlim/index.html) didn't link to a github repo. But I guess it's [here](https://github.com/tagteam/prodlim).

If you could report it to the prodlim maintainer, that would be awesome! I'm not sure I'll have time to figure out a reprex for the prodlim maintainer that narrows down to just that package, without all the pec, tidymodels overhead.
