### ISSUE TITLE
Recommended path from finding best parameters to retraining the model on full training data

### ISSUE THREAD

**Issue by konradsemsch** [tidymodels/tune#84]
I was trying to find such an example in the ```tune``` package documentation, but couldn't find one. It's obviously clear that one could simply pass the best parameters from the tuning process into a new model engine object and just train it on the full data, but it would be handy to have a helper for that. 

It could update the ```workflow()``` with specific, static parameter values that were found in the course of tuning and the user could then ```bind()``` the entire training set to the ```workflow``` OR simply use the ```fit()``` function from ```parsnip``` on such a workflow, in order to fit the final model that could be then used for making predictions. Is something like this already in scope somewhere?

**Comment by topepo** [comment]
We just added a `select_best()` to return the parameter combination with the (numerically) best results so that might help. 

The other piece needed is a mechanism to splice those values into the recipe/model/workflow object. 

Once you have that, a simple call to `fit()` should get you the final model on the entire training set. 

The splicing piece is being worked on now. It's a little confusing since we have S3 methods for `merge()` and `update()`. We might want to change those a bit. 

Anyway, here's a simple example of what you can do now:

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'xts':
#>   method     from
#>   as.zoo.xts zoo
#> ── Attaching packages ─────────────────────────── tidymodels 0.0.2 ──
#> ✔ broom     0.5.1          ✔ purrr     0.3.3     
#> ✔ dials     0.0.3.9001     ✔ recipes   0.1.7.9001
#> ✔ dplyr     0.8.3          ✔ rsample   0.0.5     
#> ✔ ggplot2   3.2.1          ✔ tibble    2.1.3     
#> ✔ infer     0.4.0          ✔ yardstick 0.0.3.9000
#> ✔ parsnip   0.0.3.9001
#> ── Conflicts ────────────────────────────── tidymodels_conflicts() ──
#> ✖ purrr::discard()  masks scales::discard()
#> ✖ dplyr::filter()   masks stats::filter()
#> ✖ dplyr::lag()      masks stats::lag()
#> ✖ ggplot2::margin() masks dials::margin()
#> ✖ dials::offset()   masks stats::offset()
#> ✖ recipes::step()   masks stats::step()
library(tune)
library(mlbench)

data(PimaIndiansDiabetes)
```

``` r

set.seed(151)
pima_rs <- vfold_cv(PimaIndiansDiabetes, repeats = 1)

tree_mod <-
  decision_tree(cost_complexity = tune(), min_n = tune()) %>%
  set_mode("classification") %>%
  set_engine("rpart")

roc_vals <- metric_set(roc_auc)

set.seed(3625)
pima_res <-
  tune_grid(diabetes ~ .,
            tree_mod,
            resamples = pima_rs,
            metrics = roc_vals)

final_param <- 
  select_best(pima_res) %>% 
  as.list()

tree_final <- exec(update, object = tree_mod, !!!final_param)
tree_final
#> Decision Tree Model Specification (classification)
#> 
#> Main Arguments:
#>   cost_complexity = 3.38609760669478e-08
#>   min_n = 4
#> 
#> Computational engine: rpart

tree_final_fit <- 
  tree_final %>% 
  fit(diabetes ~ ., data = PimaIndiansDiabetes)
```

<sup>Created on 2019-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by konradsemsch** [comment]
Ok, I was exactly looking for this one: 

```
exec(update, object = tree_mod, !!!final_param)
```

Thanks! Btw: shouldn't it be possible to pass a prepped ```recipe``` object into the ```fit``` function of parsnip so that both the formula as well as data could be processed within it? There's currently such a functionality in the good, old ```caret``` which eliminates the need for repeating code :)

**Comment by topepo** [comment]
Here's a [gist](https://gist.github.com/topepo/f734155e4e402ddd3ad3fb10b133dfe2) that has some prototype code to do the updating for recipes and models.

**Comment by konradsemsch** [comment]
That looks really cool! I made a small suggestion in the gist, but your proposal is definitely nails it already.

**Comment by topepo** [comment]
PR #86 has [`finalize_*()`](https://tidymodels.github.io/tune/reference/finalize_model.html) functions. We will eventually make a `refit_with_best()` function too.

**Comment by economer** [comment]
Perfect.

**Comment by economer** [comment]
I am teaching data science at UBC and I have based my lecture notes based on tidymodels. I was preparing my lect notes for decision-tree and random forest part and I was trying to have a better understanding of how to use tune(). This was a perfect example. 

Thanks, 
Seyed.
