### ISSUE TITLE
`eval_time` warning with `fit_best()`

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/tune#852]
It seems like `fit_best()` is triggering an `eval_time` warning when it ought not to be:

``` r
library(tidymodels)

res <-
   tune_grid(
   workflow(mpg ~ ., linear_reg(engine = "glmnet", penalty = tune())),
   bootstraps(mtcars),
   control = control_grid(save_workflow = TRUE)
)

tune_params <- select_best(res, metric = "rmse")
manual_wf <- fit_best(res, "rmse", tune_params)
#> Warning in select_best(x, metric = metric, eval_time = eval_time): `eval_time`
#> is only used for models with mode "censored regression".
```

<sup>Created on 2024-02-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

`main` tune, CRAN workflows and parsnip.

**Comment by hfrick** [comment]
That warning is triggered because `eval_time` is the third argument to `fit_best()`, so `tune_params` is treated as `eval_time` rather than the `parameters` argument.

If you provide `parameters`, neither `metric` nor `eval_time` do anything. I'm going to clarify that in the docs and via a warning.

``` r
library(tidymodels)

res <-
   tune_grid(
   workflow(mpg ~ ., linear_reg(engine = "glmnet", penalty = tune())),
   bootstraps(mtcars),
   control = control_grid(save_workflow = TRUE)
)

tune_params <- select_best(res, metric = "rmse")
manual_wf <- fit_best(res, metric = "rmse", parameters = tune_params)
```

<sup>Created on 2024-02-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by simonpcouch** [comment]
Ah, gotcha! The mistake from my end came from the fact that we had [passed the `parameters` argument by position](https://github.com/tidymodels/workflowsets/blob/5879ffd25e37a22da27826689f96d23e1f508dae/tests/testthat/test-fit_best.R#L39) but `eval_time` is now slotted into that 3rd argument.

Could we move `eval_time` to a position such that it doesn't break other arguments passed by position? I had initially assumed this placement was for consistency, but other exported functions place `eval_time` elsewhere ([fit_resamples()](https://github.com/tidymodels/tune/blob/5b0e10fac559f18c075eb4bd7020e217c6174e66/R/resample.R#L72-L78), [tune_bayes()](https://github.com/tidymodels/tune/blob/5b0e10fac559f18c075eb4bd7020e217c6174e66/R/tune_bayes.R#L234-L244), [last_fit()](https://github.com/tidymodels/tune/blob/5b0e10fac559f18c075eb4bd7020e217c6174e66/R/last_fit.R#L122-L123)).

Otherwise, I'm wondering if we should add a note in NEWS on the addition of `eval_time` arguments such that arguments passed by position will need changes, and/or add some machinery along the lines of:

```
if (inherits(eval, object_type_from_previous_intended_argument)) {
  cli_error()
}
```

**Comment by hfrick** [comment]
Looking around even further:

- Also with a placement towards the end of the argument list: [tune_grid()](https://github.com/tidymodels/tune/blob/5b0e10fac559f18c075eb4bd7020e217c6174e66/R/tune_grid.R#L292-L294), [.estimate_metrics()](https://github.com/tidymodels/tune/blob/5b0e10fac559f18c075eb4bd7020e217c6174e66/R/grid_performance.R#L61-L62)
- Sorta in the middle: [int_pctl()](https://github.com/tidymodels/tune/blob/5b0e10fac559f18c075eb4bd7020e217c6174e66/R/int_pctl.R#L69-L72)

I'm gonna update #853 to change the position of `eval_time` for `fit_best()` and we can discuss if it should change for anything else (maybe `int_pctl()`) 👍
