### ISSUE TITLE
Question: Some questions and clarifications on stackedensemble and plots using varImp

### ISSUE THREAD

**Issue by fahadshery** [tidymodels/tune#89]
Not an issue per se but there are few things I would like some clarification on:

1. Will there be an equivalent of `caret's varImp` method once the model is being fitted?
2. Suppose we built 3 models using: `xgboost, rpart, randomForest` can we turn these to `stackedEnsemble` like [this](http://docs.h2o.ai/h2o-tutorials/latest-stable/tutorials/ensembles-stacking/index.html)?
3. Would it not make sense to make the `verbose = TRUE` in the `ctrl_grid` or `ctrl_Bayes` as default option within `tune_grid` or `tune_Bayes` methods because of clarity to whats being calculated and worked on?
4. What about more verbosity for `tune_grid` and `tune_Bayes` to show which arguments of tune are being `fitted` e.g. `model 1/1 using the tuning parameters num_terms = 10, prod_degree = 2` etc.?

Apologies if these are already being dealt with but I couldn't find in the examples/docs

**Comment by topepo** [comment]
1. No. We'll rely on the `vip` package for a tidy interface for those. They just added code to work with `parsnip` objects. 

2. Not yet but that is coming. The format of our results make it easy to setup the data structures that you need for stacking. 

3. My (strong) feeling is that all code should be silent by default. It's subjective but that's how I see it. 

4. I saw that in another issue. I'd _like_ to do that for `tune_grid` especially but I don't see how to do it without the messages being 500 characters long. Please make s separate issue for that and we'll work on it after we get the basics in a stable place. One thing that we might be able to do in the short term is to have the messages retained in the `.notes` column have this additional information.  @DavisVaughan

**Comment by fahadshery** [comment]
thank you
