### ISSUE TITLE
load tune package

### ISSUE THREAD

**Issue by 2020new** [tidymodels/tune#91]
## The problem

I'm having trouble with the installation of the dev. `tune` package  

```
Error: package or namespace load failed for ‘tune’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 Namensraum ‘cli’ 1.1.0 ist bereits geladen, aber >= 1.9.9.9000 wird gefordert
```

## Reproducible example

Copy your code to the clipboard and run:

```r
devtools::install_github("tidymodels/tune")
```

**Comment by tomasu909** [comment]
I had the same issue and for whatever reason `pacman`  did the trick.

```r
pacman::p_install_gh("tidymodels/tune", force = TRUE)
```

**Comment by topepo** [comment]
This requirement is in the [description file](https://github.com/tidymodels/tune/blob/bffb40d4d01f0af1df9de12aa9e1fd935af360bf/DESCRIPTION#L48) so it's odd that it isn't installed. 

Before installing `tune`, try running: `devtools::install_github("r-lib/cli")`

**Comment by fahadshery** [comment]
I had the same issue. I had to run `devtools::install_github("r-lib/cli")` and its sorted
